
apiVersion: v1
data:
  TZ: UTC
kind: ConfigMap
metadata:
  name: pub-cm
---
{{- if .Values.secretProviderClass.create -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.secretsProvideName }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secretProviderClass.secretsManagerName }}"
        objectType: "secretsmanager"
        jmesPath:
          {{- range .Values.secretProviderClass.secretMapping }}
          - path: {{ .secretManagerKey }}
            objectAlias: {{ .secretManagerKey }}
          {{- end }}
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:
    - secretName: {{ .Values.secretProviderClass.secretsName }}
      type: Opaque
      data:
        {{- range .Values.secretProviderClass.secretMapping }}
        - objectName: {{ .secretManagerKey }}
          key: {{ .envKey}}
        {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: harborha-secret001fe
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ6ZWVrcmV1dWF0Y29udGFpbmVycmVwb3NpdG9yeS5henVyZWNyLmlvIjogewoJCQkiYXV0aCI6ICJlbVZsYTNKbGRYVmhkR052Ym5SaGFXNWxjbkpsY0c5emFYUnZjbms2ZDFKNlEwWTBOVmhEZFdaUWVVOUlla2M1V1ZwWU9HcHdOMjV0VG01aGRVbHVRVGR1UmxkV2MzSTJLMEZEVWtKTE1VcEdidz09IgoJCX0KCX0KfQ==
