
apiVersion: v1
data:
  TZ: UTC
kind: ConfigMap
metadata:
  name: pub-cm
---
  {{- if .Values.secretProviderClass.create -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.secretsProvideName }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secretProviderClass.secretsManagerName }}"
        objectType: "secretsmanager"
        jmesPath:
          {{- range .Values.secretProviderClass.secretMapping }}
          - path: {{ .secretManagerKey }}
            objectAlias: {{ .secretManagerKey }}
          {{- end }}
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:
    - secretName: {{ .Values.secretProviderClass.secretsName }}
      type: Opaque
      data:
        {{- range .Values.secretProviderClass.secretMapping }}
        - objectName: {{ .secretManagerKey }}
          key: {{ .envKey}}
        {{- end }}
  {{- end }}
---
apiVersion: v1
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJ6ZWVrcmV1dWF0Y29udGFpbmVycmVwb3NpdG9yeS5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiemVla3JldXVhdGNvbnRhaW5lcnJlcG9zaXRvcnkiLCJwYXNzd29yZCI6IndSekNGNDVYQ3VmUHlPSHpHOVlaWDhqcDdubU5uYXVJbkE3bkZXVnNyNitBQ1JCSzFKRm8ifX19
kind: Secret
metadata:
  name: harborha-secret001fe
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.zpesDigital.ingressCertificate }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.zpesDigital.groupName }}
    alb.ingress.kubernetes.io/group.order: "0"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP": 80}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/success-codes: 200-499
    alb.ingress.kubernetes.io/target-type: ip
  name: {{ .Values.ingress.zpesDigital.ingressName }}
spec:
  ingressClassName: alb
  rules:
  - host: {{ .Values.ingress.zpesDigital.url }}
    http:
      paths:
      - backend:
          service:
            name: apisix-gateway
            port:
              number: 80
        path: /
        pathType: Prefix
