apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: etcd
  name: apisix-etcd-snapshotter
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: snapshotter
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - apisix
          tolerations:
            - effect: NoSchedule
              key: app
              operator: Equal
              value: apisix
          containers:
            - command:
                - /opt/bitnami/scripts/etcd/snapshot.sh
              env:
                - name: BITNAMI_DEBUG
                  value: 'false'
                - name: ETCDCTL_API
                  value: '3'
                - name: ETCD_ON_K8S
                  value: 'yes'
                - name: MY_STS_NAME
                  value: apisix-etcd
                - name: ETCD_CLUSTER_DOMAIN
                  value: apisix-etcd-headless.apisix.svc.cluster.local
                - name: ETCD_SNAPSHOT_HISTORY_LIMIT
                  value: '3'
              image: docker.io/bitnami/etcd:3.5.4-debian-11-r14
              imagePullPolicy: IfNotPresent
              name: etcd-snapshotter
              resources:
                limits:
                  cpu: 500m
                  memory: 1Gi
                requests:
                  cpu: 100m
                  memory: 100Mi
              securityContext:
                runAsNonRoot: true
                runAsUser: 1001
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /snapshots
                  name: snapshot-volume
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 1001
          terminationGracePeriodSeconds: 30
          volumes:
            - name: snapshot-volume
              persistentVolumeClaim:
                claimName: etcd-backup
  schedule: 0 5 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
